#!/bin/bash

sibe_rt_dir=/home/xxxx/sibe
sibe_build_dir=${sibe_rt_dir}/build
sibe_bin=${sibe_build_dir}/tool/sibe

sibe_test_dir=${sibe_rt_dir}/test

#rm -rf ${sibe_build_dir}/*
cd ${sibe_build_dir}/
#rm -rf cmake  CMakeCache.txt  CMakeFiles  cmake_install.cmake  detect_cuda_archs.cu  include  __init__.py  lib  Makefile  SibeConfig.cmake  sibe_config.h  SibeConfigVersion.cmake  SibeTargets.cmake  src
cd ../
mkdir -p ${sibe_build_dir}/test

# Complie Sibe
cd ${sibe_build_dir}
cmake ..
make -j
# make install
cd ../

${sibe_bin}
